import { useState } from 'react';
import { Wrench, Car, Bike, Zap, Snowflake, BookOpen, LockKeyhole, CirclePlay, Check, ChevronRight, FileText, ArrowUpRight, GraduationCap } from 'lucide-react';
import courseData from '../data/courses.json';
import materials from '../data/materials.json';
import '../academy.css';

type CourseId = 'auto' | 'motos' | 'eletrica' | 'ar';
type Section = CourseId | 'materials';
type Lesson = {order:number;title:string;youtubeId:string;durationSeconds:number|null;optional:boolean};
type Course = {id:string;title:string;subtitle:string;modules:{order:number;title:string;lessons:Lesson[]}[]};
const courses: Course[] = courseData;
const tabs = [{id:'auto',label:'Mecânica Automotiva',icon:Car},{id:'motos',label:'Mecânica de Motos',icon:Bike},{id:'eletrica',label:'Elétrica Automotiva',icon:Zap},{id:'ar',label:'Ar-condicionado',icon:Snowflake},{id:'materials',label:'Material de apoio',icon:BookOpen}] as const;
export function previewAccess(complete: boolean, bumps: CourseId[]) { return { materials: complete || bumps.length > 0, courses: new Set<CourseId>(['auto', ...bumps]) }; }
export default function Academy() {
  const [section,setSection]=useState<Section>('auto');
  const [complete,setComplete]=useState(false);
  const [bumps,setBumps]=useState<CourseId[]>([]);
  const [selection,setSelection]=useState<Record<string,string>>({});
  const [done,setDone]=useState<string[]>([]);
  const [category,setCategory]=useState('apostila');
  const [notice,setNotice]=useState('');
  const access=previewAccess(complete,bumps);
  const course=courses.find(c=>c.id===section) || courses[0]!;
  const lessons=course.modules.flatMap(m=>m.lessons);
  const selected=lessons.find(l=>l.youtubeId===selection[course.id]) || lessons[0]!;
  const module=course.modules.find(m=>m.lessons.some(l=>l.youtubeId===selected.youtubeId))!;
  const key=course.id+':'+selected.youtubeId;
  const finished=lessons.filter(l=>done.includes(course.id+':'+l.youtubeId)).length;
  const unlocked=section==='materials'?access.materials:access.courses.has(section);
  const activeTab=tabs.find(t=>t.id===section)!;
  function navigate(id:Section){setSection(id);setNotice('');}
  return <div className="academy" lang="pt-BR">
    <header className="academy-header"><div className="academy-brand"><span className="brand-icon"><Wrench size={24}/></span><div>FORMAÇÃO MECÂNICO<span>AUTOMOTIVO</span></div></div><div className="student-label"><GraduationCap size={19}/> Área do aluno</div></header>
    <nav className="academy-nav" aria-label="Cursos e biblioteca">{tabs.map(t=><button key={t.id} onClick={()=>navigate(t.id)} aria-current={section===t.id?'page':undefined}><t.icon size={18}/><span>{t.label}</span>{!(t.id==='materials'?access.materials:access.courses.has(t.id))&&<LockKeyhole size={13} aria-label="Não adquirido"/>}</button>)}</nav>
    <aside className="demo-banner"><details><summary><span className="demo-dot"/> Prévia para avaliação <span className="demo-caption">· Simular compra</span></summary><div className="demo-settings"><label>Oferta <select value={complete?'complete':'basic'} onChange={e=>setComplete(e.target.value==='complete')}><option value="basic">Básico — R$ 10,00</option><option value="complete">Completo — R$ 27,90 / recuperação R$ 18,90</option></select></label><fieldset><legend>Cursos extras adquiridos</legend>{tabs.filter(t=>t.id!=='auto'&&t.id!=='materials').map(t=><label key={t.id}><input type="checkbox" checked={bumps.includes(t.id as CourseId)} onChange={e=>setBumps(e.target.checked?[...bumps,t.id as CourseId]:bumps.filter(id=>id!==t.id))}/>{t.label}</label>)}</fieldset><p>Qualquer curso extra também libera as apostilas e os imprimíveis. Esta simulação não confirma compras nem substitui o login e a integração Vega.</p></div></details><span className="access-badge">{access.materials?'Kit completo':'Kit básico'}</span></aside>
    <main className="academy-main"><div className="page-heading"><div><p className="eyebrow">{section==='materials'?'SUA BIBLIOTECA':'APRENDA. PRATIQUE. EVOLUA.'}</p><h1>{activeTab.label}</h1><p className="heading-description">{section==='materials'?'Seu conhecimento também acompanha você na oficina.':course.subtitle || 'Conhecimento organizado para você avançar, uma aula de cada vez.'}</p></div><span className="course-badge">{section==='materials'?'6 apostilas · 11 imprimíveis':`${course.modules.length} módulos · ${lessons.length} aulas`}</span></div>
    {!unlocked?<section className="locked-panel"><span className="lock-icon"><LockKeyhole size={32}/></span><p className="eyebrow">AMPLIE SUA FORMAÇÃO</p><h2>{section==='materials'?'Sua biblioteca completa está aqui':'Mais uma especialidade para sua carreira'}</h2><p>{section==='materials'?'As apostilas e os materiais imprimíveis estão incluídos no kit completo. A compra de qualquer curso extra também libera toda a biblioteca.':`O curso de ${activeTab.label} é adquirido separadamente. Ao comprá-lo, você também recebe acesso às apostilas e aos materiais imprimíveis do kit completo.`}</p><button className="primary-button" onClick={()=>setNotice('O link da oferta será cadastrado quando conectarmos o checkout da Vega.')}>{section==='materials'?'Conhecer o kit completo':'Conhecer este curso'}<ArrowUpRight size={17}/></button><p role="status">{notice}</p></section>:
    section==='materials'?<section><div className="library-tabs">{[['apostila','Apostilas',6],['imprimivel','Guias e checklists',11]].map(([id,label,count])=><button key={id} aria-pressed={category===id} onClick={()=>setCategory(String(id))}>{label}<span>{count}</span></button>)}</div><p className="library-note">Prévia da biblioteca. Os downloads serão disponibilizados após a configuração do acesso dos alunos.</p><div className="material-grid">{materials.filter(m=>m.kind===category).map((m,i)=><article className="material-card" key={m.file}><div className="material-cover"><div className="cover-brand"><Wrench size={17}/> FORMAÇÃO MECÂNICO</div><FileText size={38}/><h2>{m.title}</h2><span>{m.kind==='apostila'?'APOSTILA DIGITAL':'GUIA PARA IMPRIMIR'}</span><div className="cover-number">{String(i+1).padStart(2,'0')}</div></div><div className="material-info"><p>{m.file.endsWith('.pdf')?'PDF':'PNG'} · {(m.size/1024/1024).toFixed(1)} MB</p><span>Download em preparação</span></div></article>)}</div></section>:
    <div className="learning-layout"><section className="lesson-area"><div className="video-frame"><iframe key={key} src={`https://www.youtube-nocookie.com/embed/${selected.youtubeId}`} title={selected.title} allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen/></div><div className="lesson-info"><p className="eyebrow">MÓDULO {module.order} · AULA {selected.order}</p><h2>{selected.title}</h2><div className="lesson-actions"><button className={done.includes(key)?'completed-button':'primary-button'} onClick={()=>setDone(done.includes(key)?done.filter(d=>d!==key):[...done,key])} aria-pressed={done.includes(key)}><Check size={17}/>{done.includes(key)?'Aula concluída':'Marcar como concluída'}</button><a href={`https://www.youtube.com/watch?v=${selected.youtubeId}`} target="_blank" rel="noreferrer">Abrir no YouTube <ArrowUpRight size={15}/></a></div></div><button className="support-shortcut" onClick={()=>navigate('materials')}><span className="support-icon"><BookOpen size={23}/></span><span><strong>Material de apoio</strong><small>{access.materials?'Explore suas apostilas e guias de consulta.':'Disponível no kit completo ou com qualquer curso extra.'}</small></span>{access.materials?<ChevronRight size={20}/>:<LockKeyhole size={18}/>}</button></section><section className="course-outline"><div className="outline-heading"><h2>Conteúdo do curso</h2><span>{finished}/{lessons.length}</span></div><progress value={finished} max={lessons.length} aria-label="Aulas concluídas"/><p className="progress-caption" aria-live="polite">{finished} de {lessons.length} aulas concluídas nesta prévia</p>{course.modules.map(m=><details className="module" key={course.id+':'+m.order} open={undefined}><summary><span className="module-number">{String(m.order).padStart(2,'0')}</span><span><strong>{m.title}</strong><small>{m.lessons.length} aulas</small></span><ChevronRight size={17}/></summary><div>{m.lessons.map(l=><button className="lesson-row" aria-pressed={selected.youtubeId===l.youtubeId} key={l.youtubeId} onClick={()=>setSelection({...selection,[course.id]:l.youtubeId})}>{done.includes(course.id+':'+l.youtubeId)?<Check size={16}/>:<CirclePlay size={16}/>}<span>{l.order}. {l.title}{l.optional&&<small>Conteúdo opcional</small>}</span>{l.durationSeconds&&<small>{Math.floor(l.durationSeconds/60)}:{String(l.durationSeconds%60).padStart(2,'0')}</small>}</button>)}</div></details>)}</section></div>}
    </main><footer className="academy-footer">Formação Mecânico Automotivo <span>Conhecimento para transformar sua prática.</span></footer>
  </div>;
}
